#!/bin/bash
set -e

sudo chmod +x /usr/local/bin/quokspie
# Reload systemd manager configuration
sudo systemctl daemon-reload


# Optionally, you can start your service here if it should start immediately after installation
sudo systemctl start quokspie.service

# If you want the service to start on boot, enable it
sudo systemctl enable quokspie.service

echo "Quokspie daemon reloaded successfully."

exit 0